INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (1, 'fr-FR', 'firstname_form', 'Votre prénom :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (2, 'en-US', 'firstname_form', 'Your firstname :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (3, 'fr-FR', 'lastname_form', 'Votre nom :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (4, 'en-US', 'lastname_form', 'Your lastname :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (5, 'fr-FR', 'password_form', 'Votre mot de passe :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (6, 'en-US', 'password_form', 'Your password :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (7, 'fr-FR', 'connection_success', 'Connexion réussi!');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (8, 'en-US', 'connection_success', 'Connection succeded!');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (9, 'fr-FR', 'disconnection_succes', 'Dé-connexion réussi!');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (10, 'en-US', 'disconnection_succes', 'Disconnect succeded!');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (11, 'fr-FR', 'connection', 'Connexion');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (12, 'en-US', 'connection', 'Connection');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (13, 'fr-FR', 'valid', 'Valider');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (14, 'en-US', 'valid', 'Valid');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (15, 'fr-FR', 'to_disconnect', 'Se de-connecter');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (16, 'en-US', 'to_disconnect', 'To disconnect');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (17, 'fr-FR', 'disconnect', 'Deconnexion');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (18, 'en-US', 'disconnect', 'Disconnect');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (19, 'fr-FR', 'yourtoys', 'Vos jouets');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (20, 'en-US', 'yourtoys', 'Your toys');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (21, 'fr-FR', 'alltoys', 'Tous les jouets');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (22, 'en-US', 'alltoys', 'All toys');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (23, 'fr-FR', 'MPs', 'Messages privés');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (24, 'en-US', 'MPs', 'Private messages');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (25, 'fr-FR', 'register', 'Inscription');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (26, 'en-US', 'register', 'Register');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (27, 'fr-FR', 'listoftoys', 'Liste des jouets');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (28, 'en-US', 'listoftoys', 'List of toys');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (29, 'fr-FR', 'to', 'à');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (30, 'en-US', 'to', 'to');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (31, 'fr-FR', 'havenothingtoys', 'Vous n''avez aucun jouet');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (32, 'en-US', 'havenothingtoys', 'You have nothing toy');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (33, 'fr-FR', 'private', 'Privé');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (34, 'en-US', 'private', 'Private');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (35, 'fr-FR', 'public', 'Publique');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (36, 'en-US', 'public', 'Public');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (37, 'fr-FR', 'changename_form', 'Changer nom :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (38, 'en-US', 'changename_form', 'Change name :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (39, 'fr-FR', 'changedesc_form', 'Changer description :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (40, 'en-US', 'changedesc_form', 'Change description :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (41, 'fr-FR', 'changecategorie_form', 'Changer categorie :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (42, 'en-US', 'changecategorie_form', 'Change categorie :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (43, 'fr-FR', 'changestatut_form', 'Changer le statut :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (44, 'en-US', 'changestatut_form', 'Change status :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (45, 'fr-FR', 'changesuccedded', 'Modification réussi !');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (46, 'en-US', 'changesuccedded', 'Change succedded !');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (47, 'fr-FR', 'troc', 'Troquer :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (48, 'en-US', 'troc', 'Troc :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (49, 'fr-FR', 'withwhom', 'Avec qui :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (50, 'en-US', 'withwhom', 'With whom :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (51, 'fr-FR', 'whatatoy', 'Quel jouet :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (52, 'en-US', 'whatatoy', 'What a toy :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (53, 'fr-FR', 'send', 'Envoyer');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (54, 'en-US', 'send', 'Send');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (55, 'fr-FR', 'delete', 'Supprimer');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (56, 'en-US', 'delete', 'Delete');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (57, 'fr-FR', 'addatoy', 'Ajouter un jouet');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (58, 'en-US', 'addatoy', 'Add a toy');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (59, 'fr-FR', 'name_form', 'Nom :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (60, 'en-US', 'name_form', 'Name :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (61, 'fr-FR', 'desc_form', 'Description :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (62, 'en-US', 'desc_form', 'Description :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (63, 'fr-FR', 'status_form', 'Statut :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (64, 'en-US', 'status_form', 'Status :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (65, 'fr-FR', 'categorie_form', 'Catégorie :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (66, 'en-US', 'categorie_form', 'Categorie :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (67, 'fr-FR', 'picture_form', 'Image :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (68, 'en-US', 'picture_form', 'Picture :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (69, 'fr-FR', 'uploadsuccedded', 'Upload réussi!');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (70, 'en-US', 'uploadsuccedded', 'Upload succedded!');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (71, 'fr-FR', 'corresponding', 'Correspondant');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (72, 'en-US', 'corresponding', 'Corresponding');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (73, 'fr-FR', 'recipient', 'Destinataire');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (74, 'en-US', 'recipient', 'Recipient');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (75, 'fr-FR', 'object', 'Objet');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (76, 'en-US', 'object', 'Object');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (77, 'fr-FR', 'dateAndTime', 'Date et heure');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (78, 'en-US', 'dateAndTime', 'Date and Time');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (79, 'fr-FR', 'fromMessage', 'De :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (80, 'en-US', 'fromMessage', 'From :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (81, 'fr-FR', 'objectMessage', 'Objet :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (82, 'en-US', 'objectMessage', 'Object :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (83, 'fr-FR', 'contentMessage', 'Contenu :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (84, 'en-US', 'contentMessage', 'Content :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (85, 'fr-FR', 'close', 'Fermer');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (86, 'en-US', 'close', 'Close');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (87, 'fr-FR', 'open', 'Ouvrir');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (88, 'en-US', 'open', 'Open');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (89, 'fr-FR', 'add', 'Ajouter');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (90, 'en-US', 'add', 'Add');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (91, 'fr-FR', 'sendMessage_form', 'Envoyer message :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (92, 'en-US', 'sendMessage_form', 'Send a message :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (93, 'fr-FR', 'demmandAndNotification', 'Demandes et notications');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (94, 'en-US', 'demmandAndNotificati', 'Demands and notifications');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (95, 'fr-FR', 'nothingDemand', 'Aucune demande');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (96, 'en-US', 'nothingDemand', 'Nothing demand');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (97, 'fr-FR', 'wantToTroc', 'Souhaite échanger son');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (98, 'en-US', 'wantToTroc', 'Want to troc his');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (99, 'fr-FR', 'withYour', 'Avec votre');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (100, 'en-US', 'withYour', 'With your');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (101, 'fr-FR', 'nothingNotification', 'Aucune notification');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (102, 'en-US', 'nothingNotification', 'Nothing notification');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (103, 'fr-FR', 'confirmPassword_form', 'Confirmez votre mot de passe :');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (104, 'en-US', 'confirmPassword_form', 'Confirm your password : ');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (105, 'fr-FR', 'passwordDontConrresponding', 'Les mot de passes ne correcpondent pas');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (106, 'en-US', 'passwordDontConrresponding', 'Password don''t corresponding');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (107, 'fr-FR', 'registeringSuccess', 'Inscription réussi!');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (108, 'en-US', 'registeringSuccess', 'Registering succeded!');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (109, 'fr-FR', 'registering', 'S''inscrire');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (110, 'en-US', 'registering', 'Registering');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (111, 'fr-FR', 'settings', 'Paramètres');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (112, 'en-US', 'settings', 'Settings');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (113, 'fr-FR', 'changeYourPassword', 'Changer votre mot de passe');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (114, 'en-US', 'changeYourPassword', 'Change your password');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (115, 'fr-FR', 'passwordChanged', 'Mot de passe changé avec succès!');
INSERT INTO trocAngular.TEXT (IDTEXT, LANGUAGE, TEXTKEY, TEXTCONTENT) VALUES (116, 'en-US', 'passwordChanged', 'Password succesfully changed!');